name: roots_shared_lib
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.6 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^3.4.0
  flutter_svg_provider: ^1.0.7
  cached_network_image: ^3.4.1
  marquee_widget: ^1.2.0
  firebase_database: ^9.0.17
  cloud_firestore: ^3.2.0
#  file_saver: ^0.2.14

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
